### ISSUE TITLE
Two questions with regard to two variables

### ISSUE THREAD

**Issue by KevinHooah** [wdkhuans/DynamicWHAR#2]
Hi,

This work impresses me a lot! When I look into the code, there are two questions I cannot understand very well, could you clarify them for me? Thank you very much!

1. What is each row in the matrixes returned by the `edge_init` function in the `utils.py` code? I found the row number does not equal num_nodes * num_edges. Thanks!
2. I found there is a `rel_type` vector, I assume this is the "intensity of interaction" for each edge. May I ask how I can know which edge in a complete graph is the first/second/... value in the vector? Thanks!

Thank you for your time!

**Comment by wdkhuans** [comment]
Hi,

Sorry for the late reply. 

The function `edge_init` serves to return the edge vector corresponding to the relationship between each pair of nodes, where `rel_rec` returns the receive node of the edge vector and `rel_send` returns the send node of the edge vector. If the total number of nodes is $N$, then the dimension of both `rel_rec` and `rel_send` is $(N*(N-1)/2,N)$, where each row represents each edge and each column represents each node. The reason for the number of rows being $N*(N-1)/2$ is that for an undirected graph with $N$ total number of nodes, there are a total of $N*(N-1)/2$ edges. Each row is a onehot code, where the position of 1 represents the node involved in the connection. By adding up `rel_rec` and `rel_send`, each row vector corresponds to two positions with the value of 1 are the two nodes that are connected to the edge, as done in line 41 of `modules.py`.

In `rel_type`vector, each row means the same as in `rel_rec` and `rel_send`.

For Opportunity dataset, the node is in the order of  `['B','RU','RL','LU','LL']`, the edge is in the order of `[('B','RU'),('B','RL'),('B','LU'),('B','LL'), ('RU','RL'),('RU','LU'),('RU','LL'), ('RL','LU'),('RL','LL'),('LU','LL')]`.

For Realworld dataset, the node is in the order of  `['H', 'C', 'U', 'W', 'F', 'T', 'S']`, the edge  is in the order of `[('H','C'),('H','U'),('H','W'),('H','F'),('H','T'),('H','S'),('C','U'),('C','W'),('C','F'),('C','T'),('C','S'),('U','W'),('U','F'),('U','T'),('U','S'),('W','F'),('W','T'),('W','S'),('F','T'),('F','S'),('T','S')]`.

If you have any further questions, feel free to ask. You can also email me directly if you need a quick reply. Thank you a lot!

**Comment by KevinHooah** [comment]
Hi,

Thank you very much for your crystal clear answer! Now I am clear with the dimensions and their meanings.
